### ISSUE TITLE
请问CPU变频正常吗？

### ISSUE THREAD

**Issue by jjzxmmx** [LeUKi/Hackintosh-EFI-huanan_B75#1]
我的配置跟你的基本相同，我是OP+10.15.3，CPU变频问提一直没有解决（只有3档变频，而且是高频），请问你选择的是什么机型？

**Comment by LeUKi** [comment]
模拟的是iMacPro1,1 因为是台式机 所以没有做变频 你可以试试用cpufriend

**Comment by ghost** [comment]
大佬能升级一下  oc吗

**Comment by huxibei** [comment]
可以直接升级 到10.15.7 没有问题 dp 输出也不会黑屏 我的配置跟这个大佬的一毛一样的。我的oc 是0.64的好像

**Comment by LeUKi** [comment]
0.6.3应该够用了，最近考试没什么时间更新
