### ISSUE TITLE
想问下 我这个配置能用嘛？

### ISSUE THREAD

**Issue by PaoloWind** [LeUKi/Hackintosh-EFI-huanan_B75#3]
e3 1230v3
技嘉b85
8g 威刚内存
技嘉750 2g显卡

谢谢

**Comment by LeUKi** [comment]
n卡上不了

**Comment by PaoloWind** [comment]
> n卡上不了
奥 那换个显卡可以？

**Comment by LeUKi** [comment]
https://heipg.cn/tutorial/graphic-card-for-macos-2020.html
换个显卡 问题不大
