### ISSUE TITLE
同平台，想问下睡眠功能正常吗？

### ISSUE THREAD

**Issue by LuckDavid** [LeUKi/Hackintosh-EFI-huanan_B75#4]

**Comment by LeUKi** [comment]
正常的


------------------ 原始邮件 ------------------
发件人: LuckDavid ***@***.***&gt;
发送时间: 2021年10月2日 20:16
收件人: LeUKi/Hackintosh-EFI-huanan_B75 ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[LeUKi/Hackintosh-EFI-huanan_B75] 同平台，想问下睡眠功能正常吗？ (#4)
