### ISSUE TITLE
可以更新一下嘛？

### ISSUE THREAD

**Issue by WeiRen0210** [LeUKi/Hackintosh-EFI-huanan_B75#5]
同上，多谢大佬提供的efi让垃圾佬体验黑果，能更新一下oc0.7x嘛，感谢，想升级12

**Comment by LeUKi** [comment]
最近学业紧张，过段时间吧（大概到下个月？），12也才刚刚出，有挺多软件不兼容的，黑果当主力的不好随意升级，如果你是初次装建议先试试11。

**Comment by WeiRen0210** [comment]
> 学业紧张，过段时间吧（大概到下个月？，12也才出有挺多软件不力的），黑果当的不好突然升级，如果你是愿意装先学会的11。

好的，已经用了您的efi 4个月多了，为了折腾 没什么重要文件，所以想要升级😄

**Comment by LeUKi** [comment]
已更新
